language: ruby
sudo: false
rvm:
  - 2.7.2
gemfile:
  - gemfiles/activerecord-52.gemfile
  - gemfiles/activerecord-60.gemfile
  - gemfiles/activerecord-master.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/activerecord-master.gemfile
